### PR TITLE
Updated patch for 17.30

### PR DESCRIPTION
**Pull request by mainmachine**
patch section incorrect for amdgpu-pro-17.30-465504, still needs some other fixes as amdgpu.ko doesn't build...

### CODE REVIEW

**Comment by mainmachine** [comment]
Nice script, I like the idea but it's failing to build, even with the line number changes in the patch section.

Also, it'd be nice if the revert function was a little more atomic - I had to manually reinstall my kernel and a couple of xserver packages, although that might be because I'm mixing hwe-edge kernel and mesa 17.3 from git :grin: 

I know this is just a script you've got up here, probably for your own use, but I'd like me some of that undervolting and it'd be great to refine this...

**Comment by rumatoest** [comment]
Actually I have no issues with latests drivers https://www2.ati.com/drivers/linux/rhel7/amdgpu-pro-17.30-465504.tar.xz

Are you using sources from driver packages or other place? Could you give me link to the source you used.

**Comment by mainmachine** [comment]
I'm on Ubuntu, but I grabbed the Ubuntu package from the same D/L page that you grabbed yours from. Just compared the polaris10_smc.c from the ubuntu and rhel7 tar.xz's, and they're identical, so IDK why it seems like the numbering is off on that patch, nor can I say why I'm getting a fail on my end...

Are you just extracting the entire tar.xz, or are you actually installing it?

I am running the open source Mesa stack, and I'd like to continue doing that but just modify the modules needed to allow me to manipulate voltages.

Am I off base, or do you think this should be possible?

**Comment by rumatoest** [comment]
I've updated my patches.
Tested on latest amdgpu - looks like working thing

**Comment by mainmachine** [comment]
Thanks, I'll try it again - could easily be something on my end

**Pull request closed without merging**
